apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: n-body
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: n-body
  placement:
    clusterAffinity:
      clusterNames:
        - hpc-kube
        - us-azure
        - de-wide
        - l26-ugd
