apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: spin-runtime
spec:
  resourceSelectors:
    - apiVersion: node.k8s.io/v1
      kind: RuntimeClass
      name: spin
  placement:
    clusterAffinity:
      clusterNames:
        - de-wide
        - l26-ugd
